prom: missing include for 'sprintf'
> /<<PKGBUILDDIR>>/prom/src/prom_histogram_buckets.c: In function ‘double_to_str’:
> /<<PKGBUILDDIR>>/prom/src/prom_histogram_buckets.c:34:19: error: implicit declaration of function ‘sprintf’ [-Werror=implicit-function-declaration]
>    34 |         int len = sprintf(buf, "%.17g", value);
>       |                   ^~~~~~~
> /<<PKGBUILDDIR>>/prom/src/prom_histogram_buckets.c:28:1: note: include ‘<stdio.h>’ or provide a declaration of ‘sprintf’
>    27 | #include "prom_log.h"
>   +++ |+#include <stdio.h>
>    28 |
> /<<PKGBUILDDIR>>/prom/src/prom_histogram_buckets.c:34:19: error: incompatible implicit declaration of built-in function ‘sprintf’ [-Werror=builtin-declaration-mismatch]
>    34 |         int len = sprintf(buf, "%.17g", value);
>       |                   ^~~~~~~
> /<<PKGBUILDDIR>>/prom/src/prom_histogram_buckets.c:34:19: note: include ‘<stdio.h>’ or provide a declaration of ‘sprintf’